FROM registry.devneon.com.br/base-images/node:lts-neon as dependencies

WORKDIR /dependencies

COPY . /dependencies

RUN npm ci --production

FROM registry.devneon.com.br/base-images/node:lts-neon as runtime

WORKDIR /app

COPY ./src src/
COPY --from=dependencies /dependencies/node_modules node_modules/

USER node

ENTRYPOINT [ "node", "bin/server.js" ]
