/**
 * Reference:
 * https://restfulapi.net/http-status-codes/
 */
// TODO: update code based on json:api
const EnumHttpStatusCode = {
  SUCCESS_OK: 200,
  SUCCESS_CREATED: 201,
  REDIRECTION: 300,
  CLIENT_ERROR_BAD_REQUEST: 400,
  CLIENT_ERROR_UNAUTHORIZED: 401,
  CLIENT_ERROR_FORBIDEN: 403,
  CLIENT_ERROR_NOT_FOUND: 404,
  CLIENT_ERROR_PRECONDITION_FAILED: 412,
  CLIENT_ERROR_UNSUPPORTED_MEDIA_TYPE: 415,
  CLIENT_ERROR_VALIDATION: 422,
  SERVER_ERROR_INTERNAL: 500,
  SERVER_ERROR_NOT_IMPLEMENTED: 501,
};

module.exports = EnumHttpStatusCode;
